import type { Metadata } from "next";
import "./globals.css";
import PathBasedLayout from "@/components/PathBasedLayout";
import Notification from "@/components/Notification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-brand-white antialiased`}>
        <PathBasedLayout>{children}</PathBasedLayout>
        <Notification />
      </body>
    </html>
  );
}
